### ISSUE TITLE
Tests not testing txt fi;e?

### ISSUE THREAD

**Issue by gregw94542** [usspeedskating/tempus-public#18] opened 2021-02-26 02:03 UTC
**Describe the bug**
Running Tests from Visual Studio not testing NoElimQT file anymore?

 was planning on spending some time tomorrow (Friday)  entering in Donna's new Elimination tables.

I pulled LATEST..  everything built with no problems.
The I switched to "tests" and ran -no problems, Looks like a lot is happening
 Then I forced an error in the text tile NoElimQT
Reran the tests... no errors.

**Steps to Reproduce**
1. Open VIsual Studio
2. Debug Tests
3. Run - console opens and code runs, no errors
4. As sanity check, modify line in NoElimQT.txt
5. Rerun Test
6. expect error,
7. No error detect

**Expected behavior**
Console should display error if the file if modified version of NoElimQT.txt is run

Is this operator error or did the tests change?

**Comment by RobertBouillon** [comment] 2021-07-17 18:07
You're correct - this is a problem.

Closing this as a duplicate of #23

**Closed as completed by RobertBouillon** 2021-07-17 18:07 UTC
Labels: bug
